# Generated by Django 5.1.1 on 2024-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=50)),
                ("exchange", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=5, max_digits=10)),
                ("price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
